name       : dub
version    : 1.8.0
release    : 4
source     :
    - https://github.com/dlang/dub/archive/v1.8.0.tar.gz : acffbdee967a20aba2c08d2a9de6a8b23b8fb5a703eece684781758db2831d50
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - dmd
rundeps    :
    - dmd
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub

