name       : dub
version    : 1.25.0
release    : 21
source     :
    - https://github.com/dlang/dub/archive/v1.25.0.tar.gz : b9ea1a6a3d69ba4a4b522ad1e1e7f9b17c08e0d872b9a6d125ab6bdfc2b42957
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - ldc
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
