name       : dub
version    : 1.2.0
release    : 2
source     :
    - https://github.com/dlang/dub/archive/v1.2.0.tar.gz : 836caddb30ad5972a453269b027f614d51b5fd2f751a0fe63cfeb0be7388a8e9
license    : MIT
component  : programming
summary    : Package and build management system for D
description: Package and build management system for D
builddeps  :
    - pkgconfig(libcurl)
    - dmd
build      : |
    ./build.sh
install    : |
    install -Dm755 bin/dub $installdir/usr/bin/dub
    install -Dm644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
