name       : dub
version    : 1.1.0
release    : 1
source     :
    - https://github.com/dlang/dub/archive/v1.1.0.tar.gz : 8d7011a3cfcc217b22586d485b99e69496ae2deb85edfd9c80e3b4f6bb509754
license    : MIT
component  : programming
summary    : Package and build management system for D
description: Package and build management system for D
builddeps  :
    - pkgconfig(libcurl)
    - dmd
build      : |
    ./build.sh
install    : |
    install -Dm755 bin/dub $installdir/usr/bin/dub
    install -Dm644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
