name       : dub
version    : 1.11.0
release    : 6
source     :
    - https://github.com/dlang/dub/archive/v1.11.0.tar.gz : ef3f7d6ce0b726530973d9348a94fd91f9d02d30851ef3257ff538af4af571b6
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - ldc
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
