name       : dub
version    : 1.7.2
release    : 3
source     :
    - https://github.com/dlang/dub/archive/v1.7.2.tar.gz : 1801e2d8f0069ad68ef7c63ed44dc3923a8f7617fd3c9db5e5e748846b0d79cb
license    : MIT
component  : programming
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - dmd
rundeps    :
    - dmd
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub

