name       : dub
version    : 1.32.1
release    : 30
source     :
    - https://github.com/dlang/dub/archive/refs/tags/v1.32.1.tar.gz : cad53d96230d7bccd886c827d8b89ba136479ffa1a504ecd17f960c2ea50ee45
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - dmd # searches for dmd before setting the compiler
    - ldc-devel
environment: |
    export DMD=ldmd2
build      : |
    ./build.d
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
