name       : dub
version    : 1.12.1
release    : 7
source     :
    - https://github.com/dlang/dub/archive/v1.12.1.tar.gz : bd17cf67784f2ea0a2e0298761c662c80fddf6700c065f6689eb353e2144c987
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - binutils-gold
    - ldc
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
