name       : dub
version    : 1.9.0
release    : 5
source     :
    - https://github.com/dlang/dub/archive/v1.9.0.tar.gz : 48f7387e93977d0ece686106c9725add2c4f5f36250da33eaa0dbb66900f9d57
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - dmd
rundeps    :
    - dmd
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub

