name       : dub
version    : 1.16.0
release    : 9
source     :
    - https://github.com/dlang/dub/archive/v1.16.0.tar.gz : f4291dc053864b81c10dc1e9f9220aee3d4ce7ef735ecdb70de9ecbf6e0aaa5b
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - ldc
    - binutils-gold
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
