name       : dub
version    : 1.14.0
release    : 8
source     :
    - https://github.com/dlang/dub/archive/v1.14.0.tar.gz : 47c463eeaa612fda556d0291d32c8c59fd3c31dbb76142c7d997b7476773c332
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - dmd
rundeps    :
    - dmd
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
