name       : dub
version    : 1.19.0
release    : 15
source     :
    - https://github.com/dlang/dub/archive/v1.19.0.tar.gz : 84dc77f517ca1f115e05e25e8a8cdbcacbf31df281217ebac31dc974560a4ffc
license    : MIT
component  : programming.tools
summary    : Package and build management system for D
description: |
    Package and build manager for D applications and libraries.
builddeps  :
    - pkgconfig(libcurl)
    - ldc
    - binutils-gold
build      : |
    ./build.sh
install    : |
    install -Dm00755 bin/dub $installdir/usr/bin/dub
    install -Dm00644 scripts/bash-completion/dub.bash $installdir/usr/share/bash-completion/completions/dub
